### PR TITLE
Event types and event page

### PR DESCRIPTION
**Pull request by Maxgrb**
@msafih @forabi this is initial PR, to show how it may look like, make decision what data should we show for each event type and then add styles.

### CODE REVIEW

**Comment by wholesomedev** [comment]
@Maxgrb I think it looks good!

A few thoughts:

* Should we move quotes to the top?
* Can we tone the top level labels down or something?
* Can we add labels to each individual event, be it a donation, an appearance or a quote?
* Should we remove user comments entirely? (This is a big decision for which I'll open an issue under `hollowverse/hollowverse` for discussion)


@forabi can you confirm what data fields we'll need with each type?

**Comment by forabi** [comment]
For events of type `donations`, I think we are going to need:

* `doneeName` (the organization/entity that received the donation)
* `doneeUrl` (optional)
* `quote` (optional)

For events of type `appearance`, we are going to need:

* `eventName` (social event where the NP appeared, e.g. "The Oscars 2017")
* `eventUrl` (optional)
* `quote` (optional)

Also, all event types should have a `sourceUrl` and a `happenedOn`, which we already have.

@msafih By "appearance" we mean appearance in a social event, right? Not in a movie or a TV show.

**Comment by wholesomedev** [comment]
@Maxgrb We would like to try to remove event comments and fully rely on Facebook comments (https://github.com/hollowverse/hollowverse/issues/207).

**Comment by wholesomedev** [comment]
@forabi Yes, "appearance" is when the NP appears at a politics/religion oriented event.

**Comment by Maxgrb** [comment]
@msafih @forabi I've made updates. Please, check. `quote` in an event is quote of notable person, right?

**Comment by wholesomedev** [comment]
@Maxgrb I think this looks utilitarian and well segmented, which makes it easy to scan and understand and that's our main goal 😄 

Going forward, I think we should keep an eye out for opportunities to add color that won't detract from the main content. (After all, our logo is pretty colorful!)

@forabi Please let us know what you think.

**Comment by forabi** [comment]
Looks nice!

I've noticed a few issues though.

* Can we increase the contrast between the quotation mark and the background?
  screenshot_20171113_152006

* When viewed in a mobile viewport, the source links are not visible when there are too many lables. The content of this block should wrap to a new line. @msafih By the way, do we need labels for individual events?
  
  screenshot_20171112_231243

* I think the event category text in the main NP's page is too large. We should maintain the hierarchy of the headings. (NP's name should have a larger visual weight than sub titles). I'm referring to the name at the top of the page, not the one directly above the event category. For the event page, we can keep the text size.

* I am not sure we need to repeat NP's name above each category.

**Comment by wholesomedev** [comment]
> Can we increase the contrast between the quotation mark and the background?

If we increase the contrast by simply making the gray quotation background darker, then we'll be decreasing the contrast between the text and the background. And we'll also be increasing the contrast between the quote background and the rest of the page since the rest of the page is white. I don't think that's the best approach. The quotation symbol is not that important, so maybe we can leave it as is?

> When viewed in a mobile viewport, the source links are not visible when there are too many labels. The content of this block should wrap to a new line. @msafih By the way, do we need labels for individual events?

I think we need labels for individual events especially now that we're removing author comments. I'm hoping that the label will be a quick way for the reader to tell what this event says about the NP. What do you think?

But if we decide to keep the labels, then we'll need to figure out a way to handle overflowing labels.

(Side note: I do think in the future it would be nice to filter events of an NP based on their label. Like say you wanted to see all the "conservative" or "Humanitarian" things that Tom Hanks has said and done, you'd have that ability.

> I am not sure we need to repeat NP's name above each category.

I like that we're repeating the NP's name above each category. It helps with people with short attention span like me to remember what I'm reading about, especially since we don't have a floating header and such?

Anyway, this is not a strong opinion. I'm okay either way.

**Comment by Maxgrb** [comment]
@msafih @forabi thanks for the feedback. I've made update.

I've made the quote icon more contrast, but save the background. 

Agree with @msafih about person name above the event group header. It helps an user save context. I've just made the name's font a little smaller. But anyway, for me it's also not strong option.

**Comment by wholesomedev** [comment]
@Maxgrb Thanks for the updates!

I like how you've created the contrast between the quote mark and its background.

I'm not sure about the label colors though. I liked the earlier version better.

@forabi Thoughts?

**Comment by forabi** [comment]
> I'm not sure about the label colors though. I liked the earlier version better.

I agree with @msafih on the label colors.

**Comment by Maxgrb** [comment]
@msafih @forabi returned previous color of labels

**Comment by wholesomedev** [comment]
This looks good to me!

**Comment by forabi** [comment]
@msafih @Maxgrb Should we merge this and start importing the new design?

**Comment by wholesomedev** [comment]
@forabi I don't have any further comments. Your call!

**Review by forabi — APPROVED** [review]

**Pull request merged**
