### PR TITLE
Added PersonLoading and ErrorMessage components

### LINKED ISSUE #11: Provide design for other states of Notable Person's page
## Error state
A notable person's page may fail to load due to a network error or a bug in our code. We need to handle this case and display an error message to the user.

Some of the reasons a page may fail to load:
  * Notable Person is not found in our database (404)
  * Internet connection is lost or slow
  * Something is wrong on our end (API is down, code bug, etc.)

## Loading state
Because our new website is designed as a web app that calls an API, there might be some time between the page is loaded and the content is rendered. We need to indicate to the user that we are loading the content instead of showing a blank page.

### PR DESCRIPTION
**Pull request by Maxgrb**
Closes #11

### CODE REVIEW

**Comment by Maxgrb** [comment]
To get loading state just reload the page. It plays with random duration.
To get Error, reload several times. It appears randomly.

**Comment by Maxgrb** [comment]
ErrorMessage get two props: big title (can be 404 or Sorry, Opps... :) and message. As idea we can also pass an action for each of error types (Refresh, Back, etc..) and show action button.

**Comment by forabi** [comment]
I'm getting this error:

```
ERROR in ./src/components/Event/index.js
Module not found: Error: Can't resolve '../../constants/uiStrings' in '/home/f/Projects/hollowverse/design/src/components/Event'
 @ ./src/components/Event/index.js 10:0-53
 @ ./src/components/index.js
 @ ./src/containers/NotablePerson/index.js
 @ ./src/containers/index.js
 @ ./src/index.js
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8080 webpack/hot/dev-server babel-polyfill ./src/index.js

```

Looks like you need to rename `UIStrings.js` to `uiStrings.js`.

**Comment by Maxgrb** [comment]
@forabi sorry, I've forgot about case sensitive when rename files. Will fix.

**Comment by forabi** [comment]
@Maxgrb  The loading state looks great!

> As idea we can also pass an action for each of error types (Refresh, Back, etc..) and show action button.

I had this idea too. Can you please add this to the design?

As for the error state, we want the web app to feel more like a native app. I suggest that the error block (including the title, message and buttons) be vertically centered in the page. Perhaps also add some large gray warning icon or something similar instead of "Sorry"? I'm not sure.

I'm not a designer, of course. Feel free to do what you think is best. It's your call!

**Review by forabi — APPROVED** [review]

**Pull request merged**
