### PR TITLE
Convert to Storybook (and make it more compatible with the rest of our codebases)

### LINKED ISSUE #498: Use Storybook to show designs in hollowverse/design
Lack of ability to quickly view the different states of components and the rendering of components in different viewports causes unnecessary back-and-forth communication.

We can use [Storybook](https://github.com/storybooks/storybook) to show the different states of our components and to quickly view the behavior of the components in different viewport sizes.

While Storybook is usually used to showcase small components, like `<Button />`, it works just as well for showcasing a full `<App />`. So we can have:

- Homepage
- Menu (where we show the menu states within `<App />`)
  - Logged in
  - Logged out
- Notable Person page
  - Missing NP image
  - Error
- ...etc

Using Storybook in this way would require some implementation changes in `hollowverse/design`. We will need to:

1. Remove React Router
1. Lift all state up and outside of the app itself so that all of the app states can be controlled via props
1. Figure out how to load CSS properly within Storybook

We should also deploy the result to GitHub Pages

### PR DESCRIPTION
**Pull request by wholesomedev**
This PR converts hollowverse/design to a Storybook-based website. This will allow us to more easily view the different states of our app in different viewports.

I've deployed it at https://hollowverse.github.io/design/ (and from now on any merge to master will automatically be deployed to this website)

This PR also brings this codebase closer to the common Hollowverse codebase conventions. Hollowverse conventions are not better or worse than the conventions that were in this codebase, it's just good to have consistency.

CC @Maxgrb 

Closes https://github.com/hollowverse/hollowverse/issues/498

### CODE REVIEW

**Comment by wholesomedev** [comment]
Updated the link to https://hollowverse.github.io/design/ (was missing `/`)

**Review by forabi — APPROVED** [review]
LGTM!

This is really awesome! I didn't know Storybook had a viewport add-on!

Also, great use of React Context API and the ad-hoc Redux implementation :smile:

**Comment by wholesomedev** [comment]
Thanks!

I think I’m finally over my Redux obsession 😄

And Storybook worked very well for what we need here. 

One minor issue with this is that to test a certain state on a mobile device, you have to go to the source code and get the iframe src link and use that on the mobile device, which is slightly inconvenient. I opened an issue for that here https://github.com/storybooks/storybook/issues/3652

**Comment by forabi** [comment]
> I think I’m finally over my Redux obsession :smile:

LOL! I still think Redux is the most sane approach to architecturing large apps, and it gets even better when combined with reactive functional programming.

> One minor issue with this is that to test a certain state on a mobile device, you have to go to the source code and get the iframe src link and use that on the mobile device, which is slightly inconvenient.

I see. I didn't test Storybook on a phone. Hopefully it gets resolved soon.

**Pull request merged**
