### PR TITLE
Design for adding a new Quote to a Notable Person page

### PR DESCRIPTION
**Pull request by Maxgrb**
Hey @forabi @wholesomedev I have added a floated button that brings out a form for input and submitting quote. Waiting for your feedback.

### CODE REVIEW

**Comment by Maxgrb** [comment]
BTW, there is something strange with Stylelint. For CSS it requires:

`[stylelint] Expected newline after "," in a multi-line list (value-list-comma-newline-after)`

when you format it correctly and push it reformats it back into a single line. Maybe something wrong on my side.

**Comment by wholesomedev** [comment]
@Maxgrb Thanks for sending this. Here's my feedback so far:

* The button looks too strong, and it feels unrelated and foreign to our web app.
* Apologies for not being more clear, but:

  Even though we are borrowing the Floating Action Button (FAB) concept from Material UI, I don't think Material UI shadows and elevations look good on our UI since we are not actually using Material UI in the rest of the app. Should we tone these things down a bit to make the button appear more native to our app?
* The goal of https://github.com/hollowverse/hollowverse/issues/537 is to just design the button and a menu that will open when the button is clicked. We don't need to design the UX for adding a quote just yet.

  When the FAB is clicked, it needs to pop-out a menu with items. One item should say "Add a quote". When the user clicks on "Add a quote", nothing will happen (until we design that part of the experience as well)

  Again, sorry about not being more clear about that earlier.
* In Storybook, there's the "Device" dropdown. From there, you can choose "Responsive" to see what the FAB looks like on a desktop.

  I see that on a desktop, the FAB will not stay within the main container of the app. It will follow the edge of the view port, which isn't ideal in my opinion. Can we make the FAB stay within the main container of the app?

**Comment by wholesomedev** [comment]
@Maxgrb Please hold off on making the changes that I requested. We are currently thinking about the future direction of component development, and the decision may affect how we proceed with this issue.

CC @forabi

**Comment by wholesomedev** [comment]
@Maxgrb, Fawwaz (@forabi) and I discussed this and we think that we should fully adopt Material Design for Hollowverse. Doing that will allow us to use [Material-UI](https://material-ui.com/).

The challenge we are facing is that if we start adding Material-UI components to our current UI, things will not look harmonious. But this is a compromise that we've decided to live with until we migrate all of our UI to Material-UI.

So for this issue, what we need is a [Material Design Speed Dial](https://material.io/design/components/buttons-floating-action-button.html#types-of-transitions).

The Material Design Speed Dial is implemented in Material-UI [here](https://material-ui.com/lab/speed-dial/).

Can we use the Material-UI implementation in this issue?

With regard to the Material-UI SpeedDial, I see in their demo that the labels don't show up until the SpeedDial icon is hovered over. That is not ideal. We need the labels to be displayed permanently with the SpeedDial buttons.

**Comment by Maxgrb** [comment]
Hi @wholesomedev, @forabi,

Do you mean text labels (tooltips "Copy", "Save" in their demo) or action buttons (which appear when hovering on the floated button) should be displayed permanently?

I think keeping buttons opened is possible. But tooltips aren't. As I've seen their code its a part of SpeedDialAction component logic.

https://github.com/mui-org/material-ui/blob/303199d39b42a321d28347d8440d69166f872f27/packages/material-ui-lab/src/SpeedDialAction/SpeedDialAction.js

Another question – do you plan additional actions except "Add Quote" for floating button? Material Design guidelines recommend "A speed dial should include at least three options". I think there is a sense include at least two options. If we have a single option – FAB can handle it itself.

https://material.io/design/components/buttons-floating-action-button.html#types-of-transitions

**Comment by forabi** [comment]
> Do you mean text labels (tooltips "Copy", "Save" in their demo) or action buttons (which appear when hovering on the floated button) should be displayed permanently?

@Maxgrb We are actually just going to use the Speed Dial component from Material-UI as is.

> Another question – do you plan additional actions except "Add Quote" for floating button? Material Design guidelines recommend "A speed dial should include at least three options". I think there is a sense include at least two options. If we have a single option – FAB can handle it itself.

@Maxgrb We do plan to add more actions in the future. Actually, we had a rather long discussion in [#dev](https://discordapp.com/channels/308394001789353985/308394051114237952) about using the FAB and we were not really sure what the best variant of the FAB we should use. We concluded that the Speed Dial is our best option for now, even if it only has one action currently. The reason we didn't go for a simple FAB (without a Speed Dial) is because the "Add Quote" feature of Hollowverse is not easily conveyed with just an icon. I don't think users would expect that clicking a button that only has a "+" sign is going to add a new quote.

**Comment by Maxgrb** [comment]
@forabi using FAB with a single option isn't good UX as a user always have to click twice for a single action. It's like a drop-down with a single option.

The purpose of speed dial pattern is providing multiple options.

As for "+" icon – we can use another icon on FAB button that is more related to quote action.

Screenshot from Material Design Guidelines:
screen shot 2018-07-10 at 14 20 46

**Comment by forabi** [comment]
> The purpose of speed dial pattern is providing multiple options.

We are aware that this is a violation of the Material Design guidelines and is probably not the best UX. But we evaluated the options and made this trade-off. I don't think clicking twice to perform an action is necessarily a bad UX. I think it depends on the context. Anyway, I still think clicking twice is better UX than the confusion an ambiguous button with no text would cause.

> As for "+" icon – we can use another icon on FAB button that is more related to quote action.

I'm totally okay with a better icon if it can convey "Add Quote".

@wholesomedev Feel free to chime in!

**Comment by Maxgrb** [comment]
@forabi what do you think about the icon on FAB from the current PR?

Let me know if you decided to go with SpeedDial. Adding this component into the project seems quite simple, it ready-to-use and doesn't require any designing skills. Any way I can help with it :)

**Comment by wholesomedev** [comment]
@Maxgrb I think a "+" for the main FAB is OK. But we'll need an icon specifically for adding a quote on the Speed Dial Action itself.

@Maxgrb I think we still want to go with SpeedDial. And we still need your skills with selecting colors, icons, etc 😄

Color, component selection, and general UX will continue to be important as we migrate the rest of the website to Material UI.

**Comment by forabi** [comment]
> @forabi what do you think about the icon on FAB from the current PR?

When I see this icon I only think of "Quote", not "Add a Quote". I wouldn't know what the button would do if I were to click it.

**Comment by wholesomedev** [comment]
Cancelled, see https://github.com/hollowverse/design/pull/33#issuecomment-406142306

**Pull request closed without merging**
