### PR TITLE
Old content on Notable Person screen

### PR DESCRIPTION
**Pull request by Maxgrb**

### CODE REVIEW

**Comment by forabi** [comment]
@Maxgrb Nice work!

We do not need the "religion" and "political views" sections in the editorial summary. We already moved this information to the top of the page.

**Comment by wholesomedev** [comment]
@Maxgrb Nice stuff so far! 👍 

I've added the `work in progress` label to this PR. Please feel free to remove this label and [request reviews](https://help.github.com/articles/requesting-a-pull-request-review/) from me and @forabi when this PR is ready.

**Comment by Maxgrb** [comment]
Hi @wholesomedev @forabi,

I haven't found how to add you to the list of Reviewers of PR. Maybe is there any other way to request Review?

screen shot 2017-12-12 at 17 40 10

I have made various updates related to #17, #20, #21 issues. Also added Footer and static pages (About, Terms, etc.) from previous HV. Could you check?

I'm going on vacation the next week and won't be available from 18th December to 8th January. If we have some urgent things, I can make them done on this week.

**Comment by wholesomedev** [comment]
@Maxgrb, I've added you as a collaborator to this repo so maybe now you'll be able to edit labels and reviewers.

I think this is awesome work. Here's my feedback on this iteration:

# General stuff

* Can we remove the labels from every where? I don't think we'll be ready to show the label by launch time.
* The hover effect is cool, but I just wanted to let you know that it doesn't work on a touch device since there is no hover on touch devices

# Search bar

* When the search bar loses focus, can it go back to its previous state? Right now, when I click on the search icon (on the homepage), the search box is enabled and it steals focus. That's good. Then when I click away from the search box. It stays there. I don't think that's good. It should go back to showing the logo.
* Can we keep the styling of the search box the same whether it is in the focused or blurred state? Currently, it turns white with purple border when it's focused otherwise it turns gray. Can we keep it gray in both states? And can we make the text center aligned even as the user is typing?
* I'm not sure about the color of the magnifying glass icon, can we improve it?

# Homepage

Here's how the homepage looks on the iPhone 8:

<a href="https://user-images.githubusercontent.com/26730388/33920261-d07167b2-df71-11e7-8a53-e2e35d4d5640.png"></a>

* Can we show 3 NPs per row?
* Can we bring the design closer to Facebook's Friends card (image sizing, image fluidity, font-sizes, padding, etc)? [Here's](https://user-images.githubusercontent.com/26730388/33920329-3d953b2a-df72-11e7-98db-14f0af0b176e.png) how Facebook Friends card looks like on the iPhone 8. We can remove the labels from our NPs on the homepage as mentioned above. (@forabi does it make sense for us to have this layout given that we retrieve the images from Wikipedia which and those images don't have uniform aspect-ratio?)
* The pagination bar requires side-scrolling on iPhone 8 as you can see [here](https://user-images.githubusercontent.com/26730388/33920451-e82cc3c8-df72-11e7-9f8d-c0ffa053832a.png).

# NP page

* Regarding the cover image, I like the blur with the fade out effect, but to simplify the implementation of the cover image, can we have a set of cover images that we can randomly associate with NPs? We can blur them on the client side if that's more efficient (@forabi might know)
* I think we need to raise the cover image higher and/or bring the NP's name lower so that there wouldn't be contrast issues
* Should we bring the design of the NP's photo closer to Facebook's by adding a border around it, like [this](https://user-images.githubusercontent.com/26730388/33920686-1ea28392-df74-11e7-8257-5756a2524c7a.png) for example?
* Can you remove the labels from the NP page?
* I think it would be better to left align the summary
* Can you remove the quote events from the page?
* Can we put the Facebook comments section inside a card so that it gets a white background?

Other than that, I think this is great work. Thanks Max!

There's still work that needs to be done to implement the search UI/UX. If you can't complete that before going on vacation, we can maybe come up with a basic design for it until you're back.

@forabi please let us know what you think this so far.

Thanks!

**Comment by forabi** [comment]
> Also added Footer and static pages (About, Terms, etc.) from previous HV

@Maxgrb ~I can't seem to find those pages. Do you have local commits that you forgot to push?~ Never mind, I found them.

> Does it make sense for us to have this layout given that we retrieve the images from Wikipedia which and those images don't have uniform aspect-ratio?

@wholesomedev I think we can use CSS `object-fit: cover` for this, we are already doing this for the NP's page. However, because the face of the NP might not be exactly at the center of the image, some images may look weird. We can use something like [`smartcrop.js`](https://github.com/jwagner/smartcrop.js/) (probably server-side, at the time of importing the images) to crop the images to a square.

> Regarding the cover image, I like the blur with the fade out effect, but to simplify the implementation of the cover image, can we have a set of cover images that we can randomly associate with NPs? We can blur them on the client side if that's more efficient 

@wholesomedev I'm not sure what you mean. Can you please explain this?

Do we still need the RSS and Email newsletter links in the footer? We don't support RSS currently.

@Maxgrb I don't think the pagination component should be allowed to overflow. Can we reduce the number of pages displayed in the pagination component?

**Review by forabi — DISMISSED** [review]

**Review by wholesomedev — CHANGES_REQUESTED** [review]
Requested changes in the comment

**Comment by wholesomedev** [comment]
@forabi You know the blurred covered image that we have in the current design? It's basically the picture of the NP, but blurred and adjusted a bit. The blurring happens client-side. I think @Maxgrb's idea is that we should somehow derive the cover image from the NP's photo. I don't think that's easy to do, so I asked @Maxgrb to provide us with art-work that we can use as cover images. Like provide us 5-10 cover images that we would associate randomly with an NP's page. My question was should we do some processing on the image client-side or should the image be preprocessed? Now that I say it this way, I think it's obvious that having the cover images preprocessed would be the more efficient approach.

If you think deriving the cover image from the NP's photo is a good solution technically and aesthetically, then I'm okay with that approach too.

No we don't need to support RSS. We can remove that from the footer.

Oh, and `smartcrop.js` looks like a great solution! 👍

**Comment by forabi** [comment]
@Maxgrb @wholesomedev 

We'll need to update this as we don't accept reviews anymore.

screenshot_20171214_115546

We only need to display the author name and last updated date.

**Comment by Maxgrb** [comment]
@wholesomedev @forabi the cover image is easy to get right from NP picture. Actually it's NP image with CSS filters. The idea that the cover will be suit by colors and composition to NP picture. If we use static 5-10 static images for all NP pictures, they won't be suit good as dynamic.

**Comment by forabi** [comment]
> Actually it's NP image with CSS filters.

Yeah, I noticed that so that's why I was confused with @wholesomedev's suggestion.

**Comment by wholesomedev** [comment]
In the original PR #19, @Maxgrb said:

> The background (cover) image based on blurred person's photo with overlapped color gradient. It should be different for each person. So we should to check how it works with different photos.

The text above indicates that @Maxgrb thinks this is experimental and we should see how it works with different photos. I guess I'm preemptively saying that it probably won't work too well. I don't think it's working well for Arnold's image either. You can tell that the cover image is an enlarged and blurred version of Arnold's face behind a small version of his face. Is that what we want? Can't we come up with static cover images that would work well regardless of the NP's photo?

If not, how about this...

Maybe we can use a tool to pick-up the color palette of the NP's photo. Once we have the color palette, we can use it to generate cover artwork client-side with CSS or generate a static artwork server-side some how...

Anyway, if you folks think that what we currently have is fine, or at least you want to give it a try with the way it's currently designed and implemented, I'm okay with that.

**Comment by forabi** [comment]
> Maybe we can use a tool to pick-up the color palette of the NP's photo.

I like this idea. Let's give it a try.

**Comment by Maxgrb** [comment]
> Maybe we can use a tool to pick-up the color palette of the NP's photo. Once we have the color palette, we can use it to generate cover artwork client-side with CSS or generate a static artwork server-side some how...

Sounds good. What is the algorithm of generating artwork? What can be as a result? Maybe there is any examples?

Also we could try to tune blur, gradient and color params of the current cover to get better result. For example increase blur strength to get something as Spotify uses for background.

I think, the dynamic is the best accompany to NP picture by colouring and composition, than static one. Dynamic cover makes each NP page unique.

If we come with 5-10 images for all NPs, it may create wrong impression for users, that we somehow categorise NPs using cover images (an user may think like: "these actors use orange covers, and these use blue, so there should be some logic or special difference between first group and second").

Anyway, we could try static images. Just need an ideas, what it can be, some pattern, gradient or something else.

**Comment by wholesomedev** [comment]
@Maxgrb I agree that it would be better to be able to dynamically generate the cover images. 

With regard to the dynamic art, I couldn't find a good example online.

But I was inspired by what you've done with the color gradient. Your color gradient is what made me think that maybe if we pick the 5 most dominant colors from the NP's photo and splash those colors together in some pattern, maybe we'll get something that we can use as a cover image. Maybe we can create a React component that takes 5 different colors and generate some blurry artwork that we can use as a background image? Not sure...

I'm also okay with continuing to experiment with the blurring, gradient, and color parameters so that we can re-use the NP's photo as the cover image and make it look good.

**Comment by forabi** [comment]
screenshot_20171214_151025

How should we handle cases where the source link is too long and does not fit in the same line?

**Comment by Maxgrb** [comment]
> How should we handle cases where the source link is too long and does not fit in the same line?

maybe keep it on the one line and shorten with "..." `text-overflow: ellipsis`?

**Comment by Maxgrb** [comment]
@wholesomedev @forabi Please check updates. For cover I've just increased blur a little. I think, the cover may be improved more.

**Comment by wholesomedev** [comment]
@Maxgrb Awesome!

A few comments:

* The increased blurring actually solves the problem, especially on mobile width. But on desktop where the viewport is wider, I feel we need to increase the blurring further. Is it possible to automatically increase the blurring based on the viewports width?
* The "Other interesting profiles" section is too narrow on desktop, as you can see [here](https://user-images.githubusercontent.com/26730388/34003894-5f8533ae-e0ab-11e7-8475-f4e190e6abc9.png). Also, please note that we can only show 4 interesting profiles. So my question is: can we show 4 NP profiles there that take up the full width and have the size of each box be fluid so that it shrinks for smaller view ports? (For view ports that are too small, I think it's okay to have side-scrolling.)

**Comment by forabi** [comment]
@Maxgrb Why were the events removed in the NP's page? Am I missing something?

**Comment by forabi** [comment]
> And can we make the text center aligned even as the user is typing?

@wholesomedev This looks weird when the text box is empty -- the cursor will show at the center of the placeholder text:

screenshot_20171214_201152

**Comment by forabi** [comment]
> Then when I click away from the search box. It stays there. I don't think that's good. It should go back to showing the logo.

Does not that create a usability problem? How would users go back to the search box? Unless we provide a search button, I don't think this is a good idea. The search button will also work as a fallback when JavaScript is disabled, broken or slow to load.

**Comment by wholesomedev** [comment]
@forabi 

I've asked @Maxgrb to remove the quotes. And as you and I have discussed on Discord, removing the events is OK for now.

With regard to the search box, I agree with you that the `Search...` placeholder with the cursor in the middle of that doesn't look good. We have a few ways to fix that:

1. Remove the `Search...` placeholder when the input field is focused
2. Left-align the content when the input field is focused

I think the 1st option is better aesthetically. The 2nd option maybe more practical.

With regard to the usability problem: _we do_ have a search button. So that solves the problem right?

**Comment by wholesomedev** [comment]
@Maxgrb With regard to my last two comments about the increased blurring to accommodate bigger widths and the number of NPs under "Other interesting profiles", I think these are things that @forabi and I can take care of after merging.

So this LGTM! Thanks for the great work! 🎉

@forabi Please give this a pass and if you think we can take care of the remaining issues without Max's help, I think let's merge it! Max can review our adjustments after he's back from vacation.

**Review by wholesomedev — APPROVED** [review]

**Review by forabi — APPROVED** [review]

**Comment by Maxgrb** [comment]
thanks guys! See you next year 😉

**Pull request merged**
