### PR TITLE
Updating of design

### PR DESCRIPTION
**Pull request by Maxgrb**
Guys, check the first implementation of a new design based on #18 comments.

The background (cover) image based on blurred person's photo with overlapped color gradient. It should be different for each person. So we should to check how it works with different photos.

Also I have updated event's cards so make them more look like Facebook.

Added search bar in navbar. And removed person's name from titles, because now we always see the name on sticked navbar.

Waiting for your comments.

### CODE REVIEW

**Comment by wholesomedev** [comment]
@Maxgrb,

I think this is moving in the right direction. Here's my feedback so far...

With regard to the top portion of the page, I really like what you've done, but I think in the long term it would be better if we adopt more from Facebook's design. Therefore, I think we should reduce the height of the background image so that it doesn't extend as far as the text, name, and labels because it could create low-contrast issues with those.

I feel the font-sizes of the NP's name and the summary might be a bit too big. With regard to fonts, spacing, padding, margins, etc. Can we adopt more from Facebook?

For the event cards, we can stop working on those for now since we need to shift focus to the editorial summary as described in #17.

With regard to the navbar, I think it should show Hollowverse until the user starts scrolling down. As the user starts scrolling down, the navbar should morph into a search bar. You can see this behavior on Facebook's iOS app when you scroll on a user profile.

Notice that on Facebook, the page background is gray. The cards are white. The cards span the whole width of the page. Can we adopt this pattern and use it for the editorial summary card?

So for now, it would be great if you remove all the event cards and just design the editorial summary (and the associated parts that are described in #17). Again, please adopt as much as you can from Facebook's design. (For example, we can show "Other interesting profiles" the same way Facebook shows the "Friends" card)

**Comment by Maxgrb** [comment]
@wholesomedev thanks for detailed feedback. Some points.

Can't find morphing of search bar in my Facebook app. The navbar contains search bar initially and doesn't change on scroll.

I'm not sure that full-width cards will be good on wide screens. They are good on phones. Let's use fixed width for desktops (to get to get better readability) and full-width for phones?

**Comment by forabi** [comment]
> I'm not sure that full-width cards will be good on wide screens.

@wholesomedev mentioned previously that we do not want any breakpoints. We are designing for mobile phones only. In addition, we are already limiting the width of the page on larger viewports. So I don't think full-width cards will negatively impact the user experience.

Things are looking good with the latest commits.

**Comment by wholesomedev** [comment]
@Maxgrb With regard to the width, as @forabi said we already constrain the width of the page to accommodate desktop. We can continue to rely on that.

With regard to the Facebook top navbar morphing behavior: can we design something (it doesn't have to exactly match Facebook's iOS app) where the navbar goes from being the title "Hollowverse" to a search bar as the user scrolls?

**Comment by wholesomedev** [comment]
@Maxgrb I like how this is shaping up!

I have some comments mostly about events. But since we're not going to be working on events for the immediate future, I think it's not worth spending more time on that. 

I'm happy to have this merged as-is for now (pending @forabi's review) and then begin working on #17

**Comment by wholesomedev** [comment]
@forabi Just to clarify, even though I love how this is starting to look, I think there's still a lot of adjustments that we will have to make before this is ready for prime-time.

That's why I think if you don't see any glaring violations, we can get this merged and begin work on #17 and at the same time enhance the parts that will go live along with the editorial summary, such as the top bar, picture, name, cover image, etc...

**Review by forabi — APPROVED** [review]
This is looking nice!

**Pull request merged**
