### PR TITLE
UX for logging in and out

### PR DESCRIPTION
**Pull request by Maxgrb**
Hi @forabi @wholesomedev 

I have added sidebar which contains login button and the rest of menu. Also, if we pass userName and userAvatar it shows avatar, username and Sign Out button.

Let me know what do you think.

### CODE REVIEW

**Comment by wholesomedev** [comment]
Thanks for this @Maxgrb. 

image

1. I'm not sure about having the "Sign out" link right under the person's name. What if in the future, we wanted to allow the user to go to their profile page by clicking on their own name?
1. I feel the "Privacy Policy" and "Terms of Service" links have a very prominent location in this design. Can we move them to the bottom or something where they wouldn't be as visible?

Other than that, I think this looks good. The log-in experience also looks good.

@forabi any thoughts on this?

**Comment by forabi** [comment]
@Maxgrb @wholesomedev I thought we were going with a menu instead of a drawer :thinking: 

screenshot from 2018-05-19 00-07-48

Anyway, here are my thoughts:

* I think we should increase the space between the links to make them more touch-friendly
* I agree with @wholesomedev with regard to the location of "Sign out". We could use some inspiration from Twitter Lite here :wink: 
* I think we should remove the links in the footer, since they are now available in the drawer

**Comment by wholesomedev** [comment]
@forabi Isn't the difference between a menu and a drawer in this case just the animation? Or is there more difference?

**Comment by Maxgrb** [comment]
@forabi @wholesomedev my thoughts:

The menu feels more like a local navigation or context actions for a clicked object. But drawer feels like global navigation through the entire website.

The menu is more desktop pattern (ex. context menu on files). Drawer – mobile and web pattern.

The drawer can support swipe gesture to open it in future if needed.

Anyway, the drawer isn't difficult to remake to Twitter-like menu.

**Comment by forabi** [comment]
> @forabi Isn't the difference between a menu and a drawer in this case just the animation? Or is there more difference?

I don't really have a strong preference here. It's just that I remember we discussed this and concluded we want a menu. I think the drawer is fine too so never mind.

> The menu feels more like a local navigation or context actions for a clicked object. But sidebar feels like global navigation through the entire website. The menu is more desktop pattern (ex. context menu on files). Sidebar – mobile and web pattern.

@Maxgrb That's a good point, but Twitter Lite's menu _is_ global. Anyway, I do agree that a menu is not very familiar on mobile UIs compared to a drawer.

> The sidebar can support swipe gesture to open it in future if needed.

Yeah, I guess most of the complexity of the sidebar will be in getting the gestures right on various mobile browsers.

**Comment by wholesomedev** [comment]
> The menu feels more like a local navigation or context actions for a clicked object. But sidebar feels like global navigation through the entire website.

I think that makes sense. I prefer the drawer, even from an aesthetic point of view. I'm not sure why Twitter Lite went for a menu 🤔

My original concern, which applies to both a drawer or a menu, was whether it can be made to work in a robust manner in web browsers (i.e. no main window scrolling, etc). @forabi would know better about these technicalities.

**Comment by wholesomedev** [comment]
> Yeah, I guess most of the complexity of the sidebar will be in getting the gestures right on various mobile browsers.

I don't think we should try to support gestures. Making it possible to close the menu by clicking on X or *clicking outside* should be enough.

Speaking of which, would it be possible to implement the closing on clicking outside, @forabi?

**Comment by Maxgrb** [comment]
> i.e. no main window scrolling
> would it be possible to implement the closing on clicking outside

it's already done in the current component

**Comment by wholesomedev** [comment]
@Maxgrb Ah, yeah, I just noticed that it closes on clicking outside. Great!

So the other thing we need to confirm is whether it is possible to implement this drawer in a way that prevents main window scrolling. (We don't have to implement that in hollowverse/design. Implementing it in hollowverse/hollowverse should be enough.)

**Comment by Maxgrb** [comment]
@wholesomedev I have also implemented preventing of scrolling of the main window when the drawer is opened :)

Does it work in your browser? I have tested Chrome and Safari.

**Comment by wholesomedev** [comment]
@Maxgrb on iOS Safari, it is possible to scroll the main window by swiping up and down within the drawer itself

**Comment by forabi** [comment]
> So the other thing we need to confirm is whether it is possible to implement this drawer in a way that prevents main menu scrolling. 

@wholesomedev I think that's something a library like `react-aria-modal` can take care of. Implementing a drawer is not much different from a menu or a dialog.

**Comment by Maxgrb** [comment]
I suppose it can be fixed with CSS by adding to the body position:fixed and fixed coordinates when then drawer is open. I can try to fix it.

**Comment by wholesomedev** [comment]
> @wholesomedev I think that's something a library like react-aria-modal can take care off. Implementing a drawer is not much different from a menu or a dialog.

Great. We're good with the drawer then.

>I suppose it can be fixed with CSS by adding to the body position:fixed and fixed coordinates when then drawer is open. I can try to fix it.

@Maxgrb there's probably no need to fix it here. iOS Safari can be pretty stubborn. We can try to take care of that at hollowverse/hollowverse. If it doesn't work, we can come back here and think of alternatives.

@Maxgrb by the way, looking at the drawer in a mobile browser, I think UI elements are a bit too small.

image

Maybe with regard to sizing and proportions (font-sizes, margins, paddings, etc) we can copy Twitter Lite?

**Comment by Maxgrb** [comment]
@wholesomedev ok, then I'll improve sizes, update Sign Out button and remove the footer tomorrow.

About iOS – ok, let me know if you'd like to fix scrolling without libraries.

**Comment by wholesomedev** [comment]
@Maxgrb Another thing, should the button have equal length lines with slightly thicker/bigger lines, since that's what most apps have? I've noticed that the unequal length lines are sometimes used to indicate text.

image

**Comment by Maxgrb** [comment]
Hi @wholesomedev @forabi, I have made updates. Let me know your thoughts.

**Comment by wholesomedev** [comment]
@Maxgrb Thanks, I think this looks better! A few points:

1. I still feel that the proportions are not quite right on mobile. The drawer feels too big for the text being displayed. Should we reduce the width of the drawer? Should we reduce the padding from the edges?
1. The current gray color for the links doesn't grab attention. Should we use our regular text color for the links?
1. The drawer UX doesn't work very well for desktop. Can we tweak the experience to make it work well on both mobile and desktop?

**Comment by wholesomedev** [comment]
@Maxgrb Another thing:

The logout button feels like a different category of actions than going to home, about, or the contact pages. Shouldn't there be some kind of visual cue that separates the logout button from those links?

**Comment by Maxgrb** [comment]
> The drawer UX doesn't work very well for desktop. Can we tweak the experience to make it work well on both mobile and desktop?

@wholesomedev could you describe in details what exactly not very well?

**Comment by wholesomedev** [comment]
@Maxgrb 

Here's a gif (sorry about the distortions because of the low quality):

recording

The menu opens way far to the side on desktop.

Since we don't want to make a distinction between mobile and desktop in our code (by using media queries and such), I wonder if we can come up with a UX that works well both on mobile and desktop.

**Comment by Maxgrb** [comment]
@wholesomedev ah, ok, I understood the issue. I'll fix it and other points soon.

**Comment by Maxgrb** [comment]
@wholesomedev improved drawer layout and placed drawer button closer to the drawer so it should make the menu more convenient. Please check and let me know your thoughts.

**Comment by wholesomedev** [comment]
@Maxgrb Thanks for the changes.

I think the proportions look better now.

With regard to the button location, I'm not sure that moving the navbar buttons to the far ends of the screen is the best solution. Can we somehow bring the drawer closer to the content instead of moving the button away from the content? If that's not possible, then in my opinion, a menu and a button that both stay close to the content when the menu opens might be better.

**Comment by forabi** [comment]
Now that I think about it, that might be the reason why Twitter Lite has a
menu instead of a drawer: the app works great on desktop too!

**Comment by Maxgrb** [comment]
@wholesomedev @forabi yes, maybe Twitter used for that reason. I suppose they do that because it's context menu of a user profile: all menu actions are relevant to the user.

But it definitely resolves the issue of having a universal menu without of using media-queries.

So let's remake the drawer to the menu?

**Comment by wholesomedev** [comment]
Yeah, in that case I think it would be good if we can convert the drawer to
a menu :)

**Comment by Maxgrb** [comment]
@forabi @wholesomedev converted. Please check.

**Comment by wholesomedev** [comment]
@Maxgrb Thanks! LGTM!

And at this stage, if there are any small adjustments we need to make, we can probably make them in the implementation.

@forabi What do you think? (feel free to merge this if it LGTY)

@Maxgrb Could you take a look at #24 when you get a chance?

**Comment by forabi** [comment]
The menu looks great!

However, the login button is too big to fit inside the menu:

screenshot from 2018-05-22 18-42-39

Can we make it smaller? Maybe decrease the margins around the button? Or maybe just make it a regular link like the rest of the links in the menu and then make it a little more prominent with color or font weight?

**Comment by Maxgrb** [comment]
@forabi @wholesomedev fixed the button. Will look #24 tomorrow.

**Comment by forabi** [comment]
@Maxgrb @wholesomedev I made changes to the log in button UX.

* I think it's better to have a consistent position for the log in and log out buttons
* I don't think we need the log in button to have a very large visual weight. It's not really a core functionality of the website (at least for now). The old button draws too much attention.
* The new button still draws some attention but it does not indicate urgency.

screen shot 2018-05-22 at 22 10 38
screen shot 2018-05-22 at 22 10 17

**Comment by forabi** [comment]
@wholesomedev @Maxgrb Let me know what you think.

BTW I'm having problems pushing to @Maxgrb's branch. If you are OK with the changes, I can merge this and submit the changes in another PR.

**Comment by Maxgrb** [comment]
@forabi in my eyes looks much better than my version

**Comment by wholesomedev** [comment]
Agree with @Maxgrb. I think the changes look good!

**Review by forabi — APPROVED** [review]

**Pull request merged**
