### PR TITLE
UX for missing Notable Person images

### PR DESCRIPTION
**Pull request by Maxgrb**
Added placeholder for missing photos.

screen shot 2018-05-23 at 19 04 48

screen shot 2018-05-23 at 19 05 06

### CODE REVIEW

**Comment by forabi** [comment]
@Maxgrb I resolved the conflict with `master`, you will need to do a `git pull`.

**Comment by wholesomedev** [comment]
I think it looks acceptable in the Notable Person page, but it doesn't look too good when it is surrounded by gray and white colors, which is what we have in the Related People's section.

The reason it doesn't look too good there is because the gray and white colors of the image blend in with the surrounding gray and white colors.

@Maxgrb @forabi What do you think?

**Comment by Maxgrb** [comment]
@wholesomedev I have increased contrast between background and placeholder a little. Now it should look better. Let me know.

screen shot 2018-05-24 at 14 26 30

**Comment by wholesomedev** [comment]
@Maxgrb It's still blending in with the white below it. Do you think adding some gray under the white body of the avatar to separate it from the white of the card will make it look better?

**Comment by Maxgrb** [comment]
@wholesomedev personally, I like how white blending below looks aesthetically. I have added a little gray to compare. What do you think?

screen shot 2018-05-24 at 18 53 05

**Comment by wholesomedev** [comment]
@Maxgrb I think this last version looks good 👍

**Review by wholesomedev — APPROVED** [review]

**Review by forabi — APPROVED** [review]

**Pull request merged**
